#+TITLE: 猎乐如猎书：在流媒体时代重返“本地优先”
#+AUTHOR: 鹏程Frank
#+TAGS[]: "本地优先" "LifeHacker" "LifeStyle"
#+DRAFT: false
#+DATE: <2026-07-12 周日>
#+DESCRIPTION: Hunting music just like hunting books.

在这个万物皆可“云端”的时代，我们的精神生活正变得前所未有的便利，却也前所未有的轻飘。打开任何一个主流音乐App，算法像精明的侍者，精准地将符合你过往口味的旋律源源不断地推送到耳边。然而，这种被动接受的愉悦，总让人隐约感到一丝不安。

正是在这种背景下，我选择了一条看似在“开倒车”的路径：将资源端锚定在 *Bandcamp* ，将播放端留给 *foobar2000* 。

这不仅是一种技术选择，更是一场关于数字生活的自我重构。

* 猎乐如猎书：在 Bandcamp 里淘金

/Hunting music just like hunting books./

我常常觉得，在流媒体上听歌，就像是在快餐店里吃自助餐，高效却面目模糊；而从本地去淘歌，才真正配得上“捕猎”（Hunting）这个词。

*Bandcamp* 就是那个独立音乐人的大本营，或者说，它更像是一家开在深夜街角、带着霉味与墨香的独立旧书店。在这里，你不会被大厂的排行榜绑架，你得自己去翻、去听、去偶遇。很多名不见经传的音乐人在这里自由地发布他们充满粗粝感和生命力的作品，并且允许“自由定价”——这是一种极其浪漫的契约，你甚至可以免费下载到最高品质的 FLAC 或 WAV 无损文件。

对于小众音乐、电子和摇滚爱好者而言，这种体验是无与伦比的。你下载的不仅是一个几MB的音频文件，更是在进行一场审美的考古。当你顺着一个标签，在浩瀚的独立乐海里捞出一张惊艳内心的专辑时，那种多巴胺的分泌，与在旧书摊的角落里翻出一本绝版旧书的心情毫无二致。

* Apple Music：主流流媒体的克制选择

当然，在这个时代完全与流媒体世界断联并不现实。在必须选择一个主流音乐平台时，我留给了 *Apple Music* 。

在所有充斥着社交动态、短视频弹窗和花哨皮肤的流媒体软件中，Apple Music 是极其克制的。它没有花哨的社交、没有各种广告，而且原生提供了近乎严苛的高解析度无损（Hi-Res Lossless）音质。更重要的一点，在于它对“母带和曲库”的工业级尊重。

它更像是我的“国家图书馆”。当我想听那些世界主流乐坛的经典之作、交响乐或者最新发行的正版专辑时，它是一个无比靠谱的云端支撑。在这里，我不需要担心粗劣的二次压缩，它以一种高级而安静的姿态，作为我本地资料库的一块巨大延伸。
foobar2000：数字手艺人的精神避难所

如果说云端的 Apple Music 和远方的 Bandcamp 解决了“水源”问题，那么 *foobar2000* 就是我精心建造的储水池。在这个池子里，所有的水，都必须打上我个人的烙印。

坚守本地播放，我图的就是它流淌在骨子里的三点优势：

- 极致的纯净：

  当它在电脑上启动时，没有开屏雷击，没有“猜你喜欢”，只有一张干净的曲目列表。它把所有的舞台都留给了音乐本身。

- 恐怖的定制能力：

  它是软件界的乐高。刚安装时它简陋得像 Windows 98 的表格，但通过组件的拼装，你可以像素级地定制歌词、专辑墙和音频输出。亲手配置它的过程，就像是在深夜书房里亲手整理自己的书架，给每一本书贴上标签、分类上架。

- 高保真音质：

  通过 WASAPI 独占或 ASIO 输出，绕过操作系统的层层干预，将音符原汁原味地送入解碼器。这是对音乐创作者的尊重，也是对听觉的绝不妥协。

* 延伸：从“歌单”到“知识库”的同构

这种对本地软件的偏执、对模块化拼装的痴迷，其实早就不局限于我的音乐播放器了。当我回望自己的日常，我发现自己正将这种“手艺人”式的秩序感，全面推向我的数字世界。

听歌用 foobar2000，而阅读与写作，我则习惯交给 *Emacs* 里的 *Org-mode* 。

仔细想来，这两者的内核竟是如此的同构：它们在刚打开时都简陋得近乎硬核，需要你耐着性子去写配置、加插件、调参数；但它们都拥有“恐怖的定制能力”。你用代码和纯文本去搭建一个专属于自己的笔记系统，就像你用组件去魔改一个播放器界面一样。

在这个过程中，无论是淘来的无损音乐，还是逐字批注的经典文本、精心整理的思维卡片，最终都变成了纯粹的、可控的本地文件（ *Local Files* ）。它们不再是商业平台上随时可能因为版本更迭、版权到期而“灰掉”的虚无代码，而是实实在在码在自己数字书架上的藏书与唱片。

* 结语：数字主权的回归

这一切的折腾，最终指向了我的一个核心理念——“ *Local-First* ”（本地优先）。

在云端时代，我们看似拥有整个世界的曲库与信息流，实际上我们一无所有。云端的繁华只是一场随时可能蒸发的幻觉。你只是租用了暂时的使用权，而不是拥有了它们。

而当把文件下载到硬盘，用 foobar2000 严丝合缝地整理好分轨，或是把阅读心得整整齐齐地敲进本地的 .org 文本的那一刻，这些精神资产才真正属于我。它们变成了我私人数字城堡里的一砖一瓦。

即使断网，即使云端崩溃，只要通电，那些旋律依然会分毫不差地流淌出来，那些文字依然会熠熠生辉。在这个浮躁的时代，做一个“本地优先”的留守者，不为别的，只为在算法与资本的围剿中，保留一块完全由自己掌控的精神飞地。

* 我的收获

#+BEGIN_EXPORT html
<div style="margin: 20px auto; max-width: 700px; padding: 0 10px;">
  <iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/album=682277693/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/artwork=small/transparent=true/" seamless><a href="https://therallies.bandcamp.com/album/it-must-be-love-remixes">It Must Be Love (Remixes) by The Rallies</a></iframe>

<iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/album=2442995532/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/artwork=small/transparent=true/" seamless><a href="https://psicodelica.bandcamp.com/album/free-download-simply-red-sunrise-mattia-red-edit">FREE DOWNLOAD: Simply Red - Sunrise (Mattia Red Edit) by Mattia Red</a></iframe>
  
</div>
#+END_EXPORT
