#+TITLE: 2026年6月总结
#+DATE: 2026-06-30T12:36:38+08:00
#+DRAFT: false
#+TAGS[]: "随笔" "思考"
#+CATEGORIES[]: "数字花园"

* Overview

今天是2026年7月1日。我开始写这篇总结。

打开 Emacs 的 =dired mode= ，拉出自己用 =denote= 做的笔记，共20条，涉及的内容多为英语阅读。

*6月读完的书籍：*

1. [[https://book.douban.com/subject/38392258/][/The Book of Elon/]]
2. [[https://book.douban.com/subject/4898521/][《呼啸山庄》]]
3. [[https://book.douban.com/subject/37887390/][《如何自学：用更少的时间学会更多的东西（自学能力塑造一切成功者的强大内核）》]]

*6月做成的事情：*

1. 参加了[[~/org/project/2026第十七届“安徽大学”《英语世界》杯“翻译大赛”.org][2026年第十七届“安徽大学”《英语世界》杯翻译大赛]]，完成了英译汉的翻译。
2. 写了 =Tab-bar= 的使用笔记—— [[~/org/project/Emacs tab bar mode 配置.org][Emacs tab bar mode 配置]]。
   
* 我的感触

最近，我在读 /Alice's Adventures in Wonderland/ 。《爱丽丝梦游仙境》，我记得是我读初一的时候阅读一本书。那会儿，纯粹当成童书去读。

6月26日的时候，我从古登堡项目中下载了原著在蒙哥阅读器中，慢慢读一读原著，感受Lewis Caroll的笔调。

昨晚上，听了章泽天对话王强。说道王强老师，是我非常喜欢的一位，相较于新东方三驾马车的其中两位。或许，这是两个书蠹的神交与吸引。他的《读书毁了我》、《书蠹牛津消夏记》等等，而我读过他的《书蠹牛津消夏记》，里面有他写到在英国牛津饱蠹楼（Bodleian Libraries）的经历。饱蠹楼还是钱钟书钱老巧妙利用音译与意译翻译的。

听了播客后，我才得知，他还重新翻译了《爱丽丝梦游奇境》。我立马到网上去搜，没搜到平价版的。二手书直接炒到了千元。天哪！

但我最大的感受是——

#+begin_quote

吾生也有涯，而知也无涯。

#+end_quote

于是，我开始利用自己的一切时间—— *阅读* 。最近我同时在读的书籍有：

1. /How to Live an Extraordinary Life/
2. /Alice's Adventures in Wonderland/
3. 《主角》
4. 《诗经译注》
5. 《西南联大英文课》

虽然之前有过了解，multi-tasking 不算高效，但在阅读这件事上，multi-tasking 是一个较为不错的策略。《西南联大英文课》我已经读完了 Pearl S. Buck 和 Arnold Bennett 的两篇文章，笔记做的很扎实。《诗经译注》则选择慢读的方式。

怎么个慢呢？

比如我读《诗经译注》，那是读一首，背一首。

目前读到《葛覃》。我选择的是周振甫先生写的《诗经译注》，里面《毛诗序》的评注也颇有意思。

再比如说上周背的《出其东门》。《毛诗序》：“《出其东门》，闵乱也。公子五争，兵革不息，男女相弃，民人思保其室家焉。”

我就查什么是“公子五争”？

 这里的“五争”指的是春秋时期郑国的一段大内乱。郑庄公死后，他的几个儿子（祭仲立昭公，宋立厉公，之后又有子亹、子婴等）互相攻伐、篡位，郑国在几十年间陷入了极其混乱的王位争夺战，国家元气大伤。

话说回来，《毛诗序》评《关雎》有“后妃之德”。《毛诗序》评《葛覃》有“后妃之本”。想我读《人间词话》，王国维说：“一切景语皆情语”。那么《毛诗序》评《诗经》则是“一切情语，皆政语。”

老实说，我个人觉得《毛诗序》的评，过于牵强。如果剥离掉《毛诗序》赋予的政治外衣，单看这些诗歌，我认为诗歌中最纯粹的真善美才是诗歌的本真。

诗歌应该是多义的。它不为任何东西服务。孔子曾言：

#+BEGIN_QUOTE

“诗可以兴、可以观、可以群、可以怨”。

#+END_QUOTE

* 最后的话

#+BEGIN_CENTER

Respect people's time; they'll respect yours. Respect your time. People will respect you.

#+END_CENTER
