#+TITLE: 阅读随笔：我的读书经验浅谈
#+DRAFT: false
#+AUTHOR: 鹏程Frank
#+DATE: <2026-07-07 周三>
#+TAGS[]: "随笔" "读书"
#+DESCRIPTION: 不管自己身份如何，我始终是一个读书人。

#+BEGIN_QUOTE

“在大审判的那天，当那些伟大的征服者、律师和政治家走上前去接受他们的奖赏——他们的皇冠、他们的桂冠、他们不朽的名字时，上帝看到我们胳膊下夹着书走来，会转过身去，不无欣羡地对彼得说：‘看，这些人不需要奖赏。我们这里没有什么东西可以给他们。他们一生热爱读书。’”

—— 弗吉尼亚.伍尔夫《普通读者》

#+END_QUOTE

也不知多少年了，很少写散文的我，在今天这个仲夏之夜，又开始写一篇散文。我想写的是关于读书的。

许是因为“三十而立”，又或是因为“吾生也有涯，而知也无涯”，我重新回顾到阅读这条主线上来。其实说重新回归到阅读这条主线也不大妥帖，倒不如说，阅读其实从未离开过我。它更像是一条潜流，一艘夜航之船。在我被生活的琐碎、职业的身份、以及各种世俗系统裹挟着向前奔涌、穿行之时，始终在看不见的地底静静流淌、缓缓漫游。三十岁之前，我以为读书是在寻找岸。而在这个仲夏之夜，苍蝇嗡嗡闹耳，我猛然回头，才惊觉读书就是那条载我的河、搭我的船。—— 那些看似没有读书的日子，实则，我一直在用生活本身去咀嚼和消化过去读过的某一页书。

我在写这篇的时候，其实也是吃惊的。吃惊自己身份一直在变，从商业中的主管到销售，从销售到猎头，再从疫情时期的无业考编，到后疫情后的教育从业者。恰如鲍勃.齐蒙说的“人是流动的且嬗变的”。在那些高频转动的社会齿轮里，我曾以为自己快要被面目全非地拆解，像拆零件似的。在写字楼里谈论KPI、Pipeline，在未生计奔波的途中，我都曾以为自己弄丢了那个最初的自己。可直到今天动笔才发现，每当一个旧的身份碎裂、一个新的身份尚未建立的迷茫缝隙里，我全是在废墟中靠着几本书把灵魂重新拼凑起来的。职业和身份只是我在岸上穿上的不同戏装，而水面之下，支撑我没有溺亡的，依然是那些阅读留下的骸骨。

#+BEGIN_QUOTE

我注六经，六经注我。

—— 陆九渊

#+END_QUOTE

早年读书，大抵是“我注六经”的底色。总想着去皓首穷经，贪图阅读的数量，而非质量。而现在，我推崇一个“慢”字。慢意味着取舍与选择。在如今信息爆炸的时代，我选择了一种看似古典的方式——读经典。借用新东方联合创始人王强的话说：“读书只读第一流的书。”当然，这是一家之言。但不可否认，读经典会为我们节省时间，让慢读、再读有了更多的时间。因为，精神的重建不需要一万块劣质的砖头，只需要几根真正能承重的纯钢大梁。

最近，我就在慢读、再读。我读《诗经》，读一首，背一首。我读名著小说，比如 /Alice's Adventures in Wonderland/。有的是我之前读过的，但重新读一遍，背一遍，感受又是不一样的。为什么要背呢？用一个时髦 (modern) 的词——“让知识穿过身体”。

所以，我才意识到哪怕自己的外界角色如何流变，我骨子里仍是一个读书人。当然，我不仅有读书癖，也有猎书癖。

讲到猎书，我一般是按图索骥的。我很喜欢伍尔夫的意识流作品，比如今年读过的一本《达洛维夫人》，《伍尔夫读书笔记》。伍尔夫不仅仅是一个伟大的小说家，而且也是文学评论家，她的读书癖较之我而言，估计相差不大。虽然，我不清楚，但在这点上，我有我的自信。毛姆也一样。阅读是随身携带的避难所。这话说的不错。后来，我又陆续读了一些好书，比如陈彦的《主角》。这本书还在阅读，对了，还有米兰.昆德拉的《不能承受的生命之轻》。

《主角》里面的女主角原本叫易招弟，后来改名忆秦娥（因秦腔《忆秦娥.娄山关》而一战成名，走向舞台中央），再到最后改名易青娥。我从她三次更名中，看到一个生命在寻找岸、迷失于角色、最终靠筋骨立定的过程。这一过程，像极了我在那些职业名头更换的过程。

写到这，我发现，我没有像程序地写我如何如何读书，而是以一种感性的方式演化我的读书经验。在慢读、再读中......

此刻，夜静谧。只想着星星地虫声。
