#+TITLE: 为什么我要写一本开源电子书：《学习的进化》？
#+AUTHOR: 鹏程Frank
#+DRAFT: false
#+ShowToc: true
#+TocOpen: true
#+DATE: <2026-07-05 周日>
#+TAGS[]: 随笔 项目笔记
#+ShowReadingTime: true

** 项目想法

最近一段时间，我读的两本书 [[https://www.navalmanack.com/][/The Almanack of Naval Ravikant/]] 和 [[https://www.elonmuskbook.org/][/The Book of Elon/]] 这两本书一开始都是开源的。于是，我对这两本书的作者 [[https://www.ejorgenson.com/][Eric Jorgenson]] 十分好奇。

于是，我搜索了这个人的一些信息。他的个人博客上有一句话，我觉得值得思考：

#+BEGIN_QUOTE

/I collect good ideas. Then I share them with you./

#+END_QUOTE

之前关注的一个大佬李笑来，也是会开源很多他的书在GitHub上，比如[[https://github.com/ZuodaoTech/everyone-can-use-english][《人人都能用英语》]]等。

由此，我也萌生出写开源电子书的想法。

想到自己有两年的教育经验，然后平日里读了一些关于学习的书籍，我打算写一个主题—— *”学习“* 的小册子。

可我读过的大多主题是关于“学习”的书籍，多半都是以干货为主——分享一些学习方法之类的，走得是方法论这一路的。考虑到这一类的太多，如果我再去写，就是重复了。没有必要。于是，我打算从不同的角度写，也是因为灵光一闪，我的点子有了。我取名为《学习的进化》。借用小册子写得那句话：

#+BEGIN_QUOTE

用学习来理解学习，用进化来理解进化。

#+END_QUOTE

** 项目实践

开始这个项目的时候，我选择用 Emacs Org-mode 来写。带着一个问题：

*你上一次真正改变自己学习方式，是什么时候？*

不是换了一本新书，不是下载了一个新的笔记软件，而是从根本上重新思考—— *学习这件事，究竟是如何发生的？*

大多数人从未问过这个问题。我们接受的教育，教会了我们「学什么」，却几乎从不告诉我们「学习本身是什么」。

我开始进行这个项目了。

这个小册子的章节如下：

| 章节   | 主题                      |
| 前言   | 为什么学习需要【进化】      |
| 第一章 | 学习的生物学进化           |
| 第二章 | 神经元的连接：学习的物理基础 |
| 第三章 | 记忆的进化                 |
| 第四章 | 专注力的进化               |
| 第五章 | 抽象思维与概念学习          |
| 第六章 | 社会学习                  |
| 第七章 | 学习与情感                 |
| 尾声   | 学习的下一步进化           |

在两三个星期的高强度写作下，我完成了我第一个项目（链接：[[https://github.com/milteau/evolution-of-learning][《学习的进化》]]）

** 结尾

我想写这么一个作品原因如下：

1. AI时代，知识才是一个人最重要的资产。

2. 开源知识，实际上就像开源软件代码一样，可以让更多人参与进来。

3. 文明传播的方式应该是免费的，而不是设限的。
